apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.petclinic.configmap.name }}
data:
  {{ .Values.petclinic.configmap.application.properties.name }}: |
    server:
      port: {{ .Values.petclinic.server.port }}
